project:
  title: "PUBH 6860 — Principles of Bioinformatics"
  type: website
  output-dir: docs

website:
  title: "PUBH 6860 — Principles of Bioinformatics"
  site-url: https://keillyzhang.github.io/PrincBioinfo/
  sidebar:
    pinned: true
    background: "#033C5A"
    foreground: white
    border: true
    style: docked
    search: false
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Schedule
        icon: calendar
      - href: syllabus.qmd
        text: Syllabus
        icon: book
      - href: faq.qmd
        text: "FAQ"
        icon: question
      - href: links.qmd
        text: "Useful Links"
        icon: link
      - href: assignments/index.md
        text: Assignments
        icon: list-task
      - href: labs/index.qmd
        text: Labs
        icon: mortarboard
      - href: https://github.com/keillyzhang/PrincBioinfo
        text: "GitHub"
        icon: github
        target: _blank
      - href: https://blackboard.gwu.edu
        text: "Blackboard"
        icon: box-arrow-up-right
        target: _blank
      - href: https://www.zotero.org/groups/6113424/pubh-8878/library
        text: "Zotero Library"
        icon: book
        target: _blank

format:
  html:
    grid:
      sidebar-width: 250px
    css: styles.css          # optional custom styles
    toc: true
    mainfont: system-ui, sans-serif
    linkcolor: "#0190DB"
