project:
  type: website
  output-dir: docs

website:
  title: "PUBH 6860 — Principles of Bioinformatics (Fall 2025)"
  site-url: https://keillyzhang.github.io/PrincBioinfo/
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.md
      - text: Syllabus
        href: README.md
      - text: Assignments
        href: assignments/index.md
      - text: Labs
        href: labs/index.md
      - text: FAQ
        href: faq.md
      - text: Useful Links
        href: links.md
  page-footer:
    left: |
      © 2025 Milken Institute School of Public Health, GWU
    right: |
      Built with [Quarto](https://quarto.org)

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    css: styles.css
